//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banco
    {
        public int idBanco { get; set; }
        public string nombre { get; set; }
        public string sucursal { get; set; }
        public double saldoTotal { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual Cuenta Cuenta { get; set; }
    }
}
