//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Transferencia = new HashSet<Transferencia>();
        }
    
        public int idCliente { get; set; }
        public string nombreCliente { get; set; }
        public string usuario { get; set; }
        public string identificacion { get; set; }
        public string email { get; set; }
        public string tipoUsuario { get; set; }
        public string contrasena { get; set; }
        public string estado { get; set; }

        public string loginMensajeError { get; set; }

        public virtual ICollection<Transferencia> Transferencia { get; set; }

        public string ValidarUsuario()
        {
            using (WebBankingEntities15 db = new WebBankingEntities15())
            {
                var sql = from cli in db.Cliente
                          where (cli.tipoUsuario.Equals("Administrador"))
                          select cli.tipoUsuario;
                return sql.FirstOrDefault();
            }
        }
    }
}
