//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public int idCuenta { get; set; }
        public int numCuenta { get; set; }
        public string propietario { get; set; }
        public int saldo { get; set; }
        public string estado { get; set; }
        public string direccion { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Transaccion Transaccion { get; set; }
    }
}
