//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicios
    {
        public int idServicio { get; set; }
        public string nombre { get; set; }
        public int cuenta { get; set; }
        public string estado { get; set; }
        public int monto { get; set; }
    
        public virtual Transaccion Transaccion { get; set; }
    }
}
