//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class Servicio
    {
        public int idServicio { get; set; }
        public string tipoServicio { get; set; }
        public int idCuenta { get; set; }
        public int identifidor { get; set; }
        public string nombreServicio { get; set; }
        public string estado { get; set; }
        public int monto { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }


        public int ValidarServicio(string type)
        {
            using (WebBankingEntities16 db = new WebBankingEntities16())
            {
                var sql = from ser in db.Servicio
                          where (ser.tipoServicio.Equals(type))
                          select ser.idCuenta;
                return sql.FirstOrDefault();
            }
        }
        public int BuscarIdentificador(int inde)
        {
            using (WebBankingEntities16 db = new WebBankingEntities16())
            {
                var sql = from ser in db.Servicio
                          join cuen in db.Cuenta
                          on ser.idCuenta equals cuen.idCuenta
                          where (ser.identifidor.Equals(inde))
                          select ser.identifidor;
                  
                         
                return sql.FirstOrDefault();
            }
        }
    }

}
