//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Transferencia
    {
        public int idTransferencia { get; set; }
        public int idcliente { get; set; }
        public int idcuentaOrigen { get; set; }
        public string cuentaDestino { get; set; }
        public System.DateTime fechaHora { get; set; }
        public double monto { get; set; }
        public string detalle { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Cuenta Cuenta { get; set; }

        public List<int> ConsultarCuentaCliente(int obj)
        {
            using (WebBankingEntities15 db = new WebBankingEntities15())
            {
                var sql = from clien in db.Cliente
                          join cuen in db.CuentaPorCliente 
                          on clien.idCliente equals cuen.idCliente
                          where (clien.idCliente.Equals(obj))
                          select cuen.idCuenta;

                
                return sql.ToList();
            }
        }
    }
}
