//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        public int idTransaccion { get; set; }
        public byte[] fecha_hora { get; set; }
        public int cuentaOrigen { get; set; }
        public int cuentaDestino { get; set; }
        public double monto { get; set; }
        public string detalle { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual Servicios Servicios { get; set; }
    }
}
